"""init migrate

Revision ID: 2158e188a1bd
Revises: 38c4e85512a9
Create Date: 2015-10-21 16:36:59.879783

"""

# revision identifiers, used by Alembic.
revision = '2158e188a1bd'
down_revision = '38c4e85512a9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
